# frozen_string_literal: true

module Solargraph
  class YardMap
    class Macro # rubocop:disable Style/Documentation
      PROCESSABLE_DIRECTIVES = %w[method attribute parse].freeze

      class << self
        # @param directive [YARD::Tags::Directive]
        # @param method_pin [Pin::Method]
        # @return [Macro]
        def from_directive(directive, method_pin)
          macro_name = directive.tag.name.empty? ? method_pin.path.downcase : directive.tag.name
          method_object = method_object_from_pin(method_pin)
          macro_object = YARD::CodeObjects::MacroObject.create(macro_name, directive.tag.text, method_object)
          new(macro_object, method_pin, directive)
        end

        private

        # @param method_pin [Pin::Method]
        # @return [YARD::CodeObjects::MethodObject]
        def method_object_from_pin(method_pin)
          namespace_object = nil
          method_pin.each_closure do |namespace_pin|
            next if namespace_pin.name.empty?

            namespace_object = YARD::CodeObjects::NamespaceObject.new(
              namespace_object,
              namespace_pin.name.to_sym
            )
          end
          YARD::CodeObjects::MethodObject.new(namespace_object, method_pin.name)
        end
      end

      # @return [YARD::Tags::MacroDirective]
      attr_reader :directive
      # @return [YARD::CodeObjects::MacroObject]
      attr_reader :macro_object

      # @param macro [YARD::MacroObject]
      # @param method_pin [Pin::Method]
      # @param directive [YARD::Tags::Directive]
      def initialize(macro_object, method_pin, directive)
        @macro_object = macro_object
        @method_pin = method_pin
        @directive = directive
      end

      # @return [String]
      def name
        @directive.tag.name
      end

      # @return [String]
      def text
        @directive.tag.text
      end

      # @return [YARD::Tags::Tag]
      def tag
        @directive.tag
      end

      # (see YARD::MacroObject#expand)
      def expand(call_params = [], full_source = '', block_source = '')
        macro_object.expand(call_params, full_source, block_source)
      end

      # @param method_call_pin [Pin::Ephemeral::ClassMethodSend]
      # @return [Array<YARD::Tags::MethodDirective>] - yardoc generated by the macro
      def generate_yardoc_from(class_method_send)
        expanded_comment = expand([class_method_send.name, *class_method_send.arguments.map(&:value).map(&:to_s)], class_method_send.code)
        Solargraph::Source.parse_docstring(expanded_comment).directives.select do |directive|
          PROCESSABLE_DIRECTIVES.include?(directive.tag.tag_name)
        end.each do |directive|
          if class_method_send.comments.length.positive? && directive.tag.tag_name != 'parse'
            directive.tag.text += "\n#{class_method_send.comments}"
          end
        end
      end
    end
  end
end
