# frozen_string_literal: true

module Solargraph
  class YardMap
    class Macro # rubocop:disable Style/Documentation
      class << self
        # @param directive [YARD::Tags::Directive]
        # @param method_pin [Pin::Method]
        # @return [Macro]
        def from_directive(directive, method_pin)
          method_object = method_object_from_pin(method_pin)
          macro_object = YARD::CodeObjects::MacroObject.create(directive.tag.name, directive.tag.text, method_object)
          new(macro_object, method_pin, directive)
        end

        private

        # @param method_pin [Pin::Method]
        # @return [YARD::CodeObjects::MethodObject]
        def method_object_from_pin(method_pin)
          namespace_object = nil
          method_pin.each_closure do |namespace_pin|
            next if namespace_pin.name.empty?

            namespace_object = YARD::CodeObjects::NamespaceObject.new(
              namespace_object,
              namespace_pin.name.to_sym
            )
          end
          YARD::CodeObjects::MethodObject.new(namespace_object, method_pin.name)
        end
      end

      # @return [YARD::Tags::MacroDirective]
      attr_reader :directive
      # @return [YARD::CodeObjects::MacroObject]
      attr_reader :macro_object

      # @param macro [YARD::MacroObject]
      # @param method_pin [Pin::Method]
      # @param directive [YARD::Tags::Directive]
      def initialize(macro_object, method_pin, directive)
        @macro_object = macro_object
        @method_pin = method_pin
        @directive = directive
      end

      # @return [String]
      def name
        @directive.tag.name
      end

      # @return [String]
      def text
        @directive.tag.text
      end

      # @return [YARD::Tags::Tag]
      def tag
        @directive.tag
      end

      # (see YARD::MacroObject#expand)
      def expand(call_params = [], full_source = '', block_source = '')
        macro_object.expand(call_params, full_source, block_source)
      end

      # @param method_call_code [String]
      # @return [Array<YARD::Tags::MethodDirective>] - yardoc generated by the macro
      def generate_yardoc_from(code)
        return [] unless @method_pin.is_a?(Pin::Method)

        parsed_node = Parser.parse(code)
        method_name = parsed_node.children[0].to_s
        method_params = parsed_node&.children[1]&.children&.map { |n| n.children[0].to_s if n }&.compact # method params
        expanded_comment = expand([method_name, *method_params], code)
        Solargraph::Source.parse_docstring(expanded_comment).directives.select do |directive|
          directive.tag.tag_name == 'method'
        end
      end
    end
  end
end
